import type { Route } from 'next'

export const nextUrls = {
  ROOT: '/',
  AUTH: '/auth',
  LOGIN: '/auth/sign-in',
  REGISTER: '/auth/sign-up',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  LOGOUT: '/auth/sign-out',
  ACCOUNT: '/account',
  PROFILE: '/account/profile',
  SECURITY: '/account/security',
  SESSION: '/account/session',
  STORE: '/store',
  PRODUCTS: '/store/products',
  PRODUCT: '/store/products/[productId]',
  STUDIO: '/studio',
  BLOG: '/blog',
  POST: '/blog/[slug]',
  CATEGORIES: '/blog/categories',
  CATEGORY: '/blog/categories/[category]',
  TAGS: '/blog/tags',
  TAG: '/blog/tags/[tag]',
  ABOUT: '/about',
  CONTACT: '/contact',
  LEGAL: '/legal',
  LICENSE: '/legal/licenses',
  PRIVACY: '/legal/privacy-policy',
  TERMS: '/legal/terms-of-service',
  COOKIES: '/legal/cookies-policy',
  SUPPORT: '/support',
  SUPPORT_CONTACT: '/support/contact-support',
  FAQ: '/support/faq',
  HELP_CENTER: '/support/help-center',
  TICKETS: '/support/tickets',
  TICKET: '/support/tickets/[ticketId]',
} as const satisfies Record<Route, string>

export type NextUrls = typeof nextUrls
